### ISSUE TITLE
[BUG] Multiplayer Auto Raider

### ISSUE THREAD

**Issue by GEKTHEBOSS** [invokehub/invokestatic#90] opened 2015-01-19 12:26 UTC
Every time i close and re open cocabot (12.6) this checkbox have to be ticked!

Thanks for your work!

**Comment by giraffesyo** [comment] 2015-01-19 15:23
Duplicate of #83

**Comment by invokehub** [comment] 2015-01-20 04:16
This is intentional, @GEKTHEBOSS.  See #83.

**Closed by invokehub** 2015-01-20 04:16 UTC
