### ISSUE TITLE
[BUG] Pause/Resume + [SUGGESTION]

### ISSUE THREAD

**Issue by GEKTHEBOSS** [invokehub/invokestatic#92] opened 2015-01-19 12:48 UTC
pause/resume is broken, not always works!

suggestion is that you can change settings while paused, or you must stop and re open wait ALLATORI etc.

**Comment by giraffesyo** [comment] 2015-01-19 15:27
Duplicate of #65  and #54, also reference #58

**Closed** 2015-01-20 04:15 UTC
