### ISSUE TITLE
Beta 10 - Auto Donate doesn't always reconize that there are multiple pending donate/request

### ISSUE THREAD

**Issue by mnestroy** [invokehub/invokestatic#56] opened 2015-01-09 19:21 UTC
I wasn't able to grab a screen shot, but I witnessed the bot goto the clan chat and there was 3 pending requests.

I had plenty of troops.

The bot only filled the first 2 request and then closed the chat window and carried on with next function.

**Comment by invokehub** [comment] 2015-01-09 20:47
Duplicate of #50

**Closed by invokehub** 2015-01-09 20:47 UTC
Labels: duplicate
